# Generated by Django 5.2.4 on 2025-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comment_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="hobbies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="newsletter_subscription",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
