# Generated by Django 5.2.4 on 2025-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_date_of_birth_user_interests_user_profession_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hobbies",
        ),
    ]
