# Generated by Django 5.2.4 on 2025-07-25 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_sitesetting_tag_category_post_media_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
